import { Task, TeamMember, Project } from "@/lib/types/task";

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: "user-1",
    name: "Anna Schmidt",
    email: "anna@example.com",
    avatar_url: null,
  },
  {
    id: "user-2",
    name: "Max Mustermann",
    email: "max@example.com",
    avatar_url: null,
  },
  {
    id: "user-3",
    name: "Lisa Weber",
    email: "lisa@example.com",
    avatar_url: null,
  },
  {
    id: "user-4",
    name: "Tom Fischer",
    email: "tom@example.com",
    avatar_url: null,
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "project-1",
    name: "Website Relaunch",
    description: "Komplette Neugestaltung der Unternehmenswebsite mit modernem Design und verbesserter Nutzererfahrung.",
    team_id: "team-1",
    created_at: "2026-01-15T10:00:00Z",
  },
  {
    id: "project-2",
    name: "Mobile App",
    description: "Native Mobile App fuer iOS und Android mit den wichtigsten Features der Web-Plattform.",
    team_id: "team-1",
    created_at: "2026-01-20T14:00:00Z",
  },
  {
    id: "project-3",
    name: "API Integration",
    description: "Integration von Drittanbieter-APIs fuer Zahlungsabwicklung und Benachrichtigungen.",
    team_id: "team-1",
    created_at: "2026-02-01T09:00:00Z",
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    project_id: "project-1",
    title: "Wireframes erstellen",
    description: "Wireframes fuer die Startseite, Produktseite und Kontaktseite erstellen.",
    assigned_to: "user-1",
    status: "completed",
    due_date: "2026-02-10T00:00:00Z",
    created_at: "2026-01-16T10:00:00Z",
    updated_at: "2026-02-09T15:00:00Z",
  },
  {
    id: "task-2",
    project_id: "project-1",
    title: "Design-System definieren",
    description: "Farben, Typografie, Spacing und Komponenten-Bibliothek festlegen.",
    assigned_to: "user-1",
    status: "in_progress",
    due_date: "2026-02-20T00:00:00Z",
    created_at: "2026-01-18T11:00:00Z",
    updated_at: "2026-02-12T09:00:00Z",
  },
  {
    id: "task-3",
    project_id: "project-1",
    title: "Frontend-Entwicklung Startseite",
    description: "Implementierung der Startseite basierend auf den finalen Designs.",
    assigned_to: "user-2",
    status: "to_do",
    due_date: "2026-03-01T00:00:00Z",
    created_at: "2026-01-20T14:00:00Z",
    updated_at: "2026-01-20T14:00:00Z",
  },
  {
    id: "task-4",
    project_id: "project-1",
    title: "SEO-Optimierung",
    description: "Meta-Tags, strukturierte Daten und Performance-Optimierung.",
    assigned_to: null,
    status: "to_do",
    due_date: "2026-03-15T00:00:00Z",
    created_at: "2026-01-22T16:00:00Z",
    updated_at: "2026-01-22T16:00:00Z",
  },
  {
    id: "task-5",
    project_id: "project-1",
    title: "Content-Migration",
    description: "Bestehende Inhalte in das neue CMS uebertragen und formatieren.",
    assigned_to: "user-3",
    status: "to_do",
    due_date: "2026-02-12T00:00:00Z",
    created_at: "2026-01-25T10:00:00Z",
    updated_at: "2026-01-25T10:00:00Z",
  },
  {
    id: "task-6",
    project_id: "project-1",
    title: "Browser-Testing",
    description: "Kompatibilitaetstests in Chrome, Firefox, Safari und Edge durchfuehren.",
    assigned_to: "user-4",
    status: "in_progress",
    due_date: "2026-02-14T00:00:00Z",
    created_at: "2026-02-01T09:00:00Z",
    updated_at: "2026-02-13T11:00:00Z",
  },
  {
    id: "task-7",
    project_id: "project-2",
    title: "App-Architektur planen",
    description: "Technische Architektur und Projektstruktur fuer die Mobile App festlegen.",
    assigned_to: "user-2",
    status: "completed",
    due_date: "2026-02-05T00:00:00Z",
    created_at: "2026-01-21T10:00:00Z",
    updated_at: "2026-02-04T16:00:00Z",
  },
  {
    id: "task-8",
    project_id: "project-2",
    title: "Login-Screen implementieren",
    description: "Login- und Registrierungs-Screens mit Formular-Validierung implementieren.",
    assigned_to: "user-2",
    status: "in_progress",
    due_date: "2026-02-18T00:00:00Z",
    created_at: "2026-02-06T10:00:00Z",
    updated_at: "2026-02-14T14:00:00Z",
  },
];
